2020-10-06 21:00:04.701886: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Running tests under Python 3.6.12: C:\ProgramData\Anaconda3\envs\keras\python.exe
[ RUN      ] AdagradOptimizerTest.testBasic
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W1006 21:00:07.780081 23012 deprecation.py:506] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py:76: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W1006 21:00:07.795700 23012 deprecation.py:506] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py:76: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[  FAILED  ] AdagradOptimizerTest.testBasic
[ RUN      ] AdagradOptimizerTest.testBasicCallableParams
2020-10-06 21:00:07.810509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-06 21:00:07.944595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:07.945131: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:07.950077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:07.954880: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:07.956654: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:07.962913: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:07.967655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:07.979594: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:07.980573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:07.981159: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-06 21:00:07.994544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:07.995117: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:07.995455: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:07.995856: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:07.996211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:07.996549: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:07.996901: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:07.997247: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:07.998117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.053447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.053859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.054103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.054903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testBasicCallableParams
[ RUN      ] AdagradOptimizerTest.testBasicLocked
[  FAILED  ] AdagradOptimizerTest.testBasicLocked
[ RUN      ] AdagradOptimizerTest.testBasicResource
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W1006 21:00:09.561671 23012 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2020-10-06 21:00:09.565802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.566343: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.566720: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.567088: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.567449: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.567808: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.568151: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.568501: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.569093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.569399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.569751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.569974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.570477: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testBasicResource
[ RUN      ] AdagradOptimizerTest.testDynamicShapeVariableWithCallableInit
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\variables.py:2825: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W1006 21:00:09.592919 23012 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\variables.py:2825: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
[  FAILED  ] AdagradOptimizerTest.testDynamicShapeVariableWithCallableInit
[ RUN      ] AdagradOptimizerTest.testDynamicShapeVariable_Ok
2020-10-06 21:00:09.612319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.612842: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.613206: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.613555: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.613896: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.614234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.614576: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.614918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.615489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.615797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.616162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.616406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.617003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] AdagradOptimizerTest.testDynamicShapeVariable_Ok
[ RUN      ] AdagradOptimizerTest.testMinimizeSparseResourceVariable
2020-10-06 21:00:09.620835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.621350: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.621691: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.622037: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.622373: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.622805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.623149: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.623497: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.624113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.624418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.624773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.624992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.625483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testMinimizeSparseResourceVariable
[ RUN      ] AdagradOptimizerTest.testSharing
2020-10-06 21:00:09.654730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.655251: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.655629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.655996: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.656356: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.656725: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.657071: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.657431: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.658012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.658316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.658671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.658891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.659380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testSharing
[ RUN      ] AdagradOptimizerTest.testSparseBasic
2020-10-06 21:00:09.670760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.671295: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.671638: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.671983: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.672324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.672675: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.673025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.673367: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.673935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.674240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.674601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.674826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.675314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testSparseBasic
[ RUN      ] AdagradOptimizerTest.testSparseRepeatedIndices
2020-10-06 21:00:09.688397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.688909: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.689250: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.689607: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.689953: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.690297: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.690641: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.690985: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.691551: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.691847: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.692199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.692422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.692921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testSparseRepeatedIndices
[ RUN      ] AdagradOptimizerTest.testSparseRepeatedIndicesResourceVariable
2020-10-06 21:00:09.705756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.706272: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.706611: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.706954: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.707304: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.707659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.708017: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.708364: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.708925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.709221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.709573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.709797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.710279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testSparseRepeatedIndicesResourceVariable
[ RUN      ] AdagradOptimizerTest.testSparseStability
2020-10-06 21:00:09.737083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.737604: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.737950: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.738296: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.738632: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.738978: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.739320: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.739680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.740249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.740555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.740907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.741130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.741632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testSparseStability
[ RUN      ] AdagradOptimizerTest.testTensorLearningRate
2020-10-06 21:00:09.750837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 21:00:09.751353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 21:00:09.751709: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 21:00:09.752063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 21:00:09.752415: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 21:00:09.752760: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 21:00:09.753102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 21:00:09.753444: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 21:00:09.754008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 21:00:09.754305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 21:00:09.754667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 21:00:09.754895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 21:00:09.755381: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] AdagradOptimizerTest.testTensorLearningRate
[ RUN      ] AdagradOptimizerTest.test_session
[  SKIPPED ] AdagradOptimizerTest.test_session
======================================================================
ERROR: testBasic (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testBasic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adagrad_test.py", line 171, in testBasic
    self.doTestBasic(use_locking=False)
  File "adagrad_test.py", line 125, in doTestBasic
    zip([grads0, grads1], [var0, var1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testBasicCallableParams (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testBasicCallableParams
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adagrad_test.py", line 189, in testBasicCallableParams
    use_locking=False, use_resource=True, use_callable_params=True)
  File "adagrad_test.py", line 151, in doTestBasic
    ada_opt.apply_gradients(zip([grads0, grads1], [var0, var1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testBasicLocked (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testBasicLocked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adagrad_test.py", line 195, in testBasicLocked
    self.doTestBasic(use_locking=True)
  File "adagrad_test.py", line 125, in doTestBasic
    zip([grads0, grads1], [var0, var1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testBasicResource (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testBasicResource
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1080, in decorated
    f(self, *args, **kwargs)
  File "adagrad_test.py", line 179, in testBasicResource
    self.doTestBasic(use_locking=False, use_resource=True)
  File "adagrad_test.py", line 125, in doTestBasic
    zip([grads0, grads1], [var0, var1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testDynamicShapeVariableWithCallableInit (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testDynamicShapeVariableWithCallableInit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1272, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 667, in testDynamicShapeVariableWithCallableInit
    zip([grads0], [var0]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testMinimizeSparseResourceVariable (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testMinimizeSparseResourceVariable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 217, in testMinimizeSparseResourceVariable
    sgd_op = adagrad.AdagradOptimizer(1.0).minimize(loss)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 413, in minimize
    name=name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testSharing (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testSharing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 569, in testSharing
    zip([grads0, grads1], [var0, var1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testSparseBasic (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testSparseBasic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 331, in testSparseBasic
    zip([grads0, grads1], [var0, var1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testSparseRepeatedIndices (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testSparseRepeatedIndices
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 397, in testSparseRepeatedIndices
    [(grad_repeated_index, repeated_index_update_var)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testSparseRepeatedIndicesResourceVariable (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testSparseRepeatedIndicesResourceVariable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 447, in testSparseRepeatedIndicesResourceVariable
    2.0).minimize(loss_repeated)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 413, in minimize
    name=name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testSparseStability (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testSparseStability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 515, in testSparseStability
    ada_update = ada_opt.apply_gradients(zip([grads0], [var0]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: testTensorLearningRate (__main__.AdagradOptimizerTest)
AdagradOptimizerTest.testTensorLearningRate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "adagrad_test.py", line 263, in testTensorLearningRate
    zip([grads0, grads1], [var0, var1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\adagrad.py", line 80, in _create_slots
    "accumulator", self._name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1138, in _get_or_make_slot_with_initializer
    slot_variable=new_slot_variable)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 1170, in _restore_slot_variable
    deferred_restorations = self._deferred_slot_restorations.get(
AttributeError: 'NoneType' object has no attribute 'get'

----------------------------------------------------------------------
Ran 14 tests in 1.985s

FAILED (errors=12, skipped=1)
