2020-10-04 18:14:34.981852: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
============================= test session starts =============================
platform win32 -- Python 3.6.12, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\mutation\Desktop\testcase\tests\keras\utils
plugins: flaky-3.7.0
collected 1 item

layer_utils_test.py F                                                    [100%]

================================== FAILURES ===================================
____________________________ test_convert_weights _____________________________

    def test_convert_weights():
        def get_model(shape, data_format):
            model = Sequential()
            model.add(Conv2D(filters=2,
                             kernel_size=(4, 3),
                             input_shape=shape,
                             data_format=data_format))
            model.add(Flatten())
            model.add(Dense(5))
            return model
    
        for data_format in ['channels_first', 'channels_last']:
            if data_format == 'channels_first':
                shape = (3, 5, 5)
                target_shape = (5, 5, 3)
                prev_shape = (2, 3, 2)
                flip = lambda x: np.flip(np.flip(x, axis=2), axis=3)
                transpose = lambda x: np.transpose(x, (0, 2, 3, 1))
                target_data_format = 'channels_last'
            elif data_format == 'channels_last':
                shape = (5, 5, 3)
                target_shape = (3, 5, 5)
                prev_shape = (2, 2, 3)
                flip = lambda x: np.flip(np.flip(x, axis=1), axis=2)
                transpose = lambda x: np.transpose(x, (0, 3, 1, 2))
                target_data_format = 'channels_first'
    
            model1 = get_model(shape, data_format)
            model2 = get_model(target_shape, target_data_format)
            conv = K.function([model1.input], [model1.layers[0].output])
    
            x = np.random.random((1,) + shape)
    
            # Test equivalence of convert_all_kernels_in_model
            convout1 = conv([x])[0]
>           layer_utils.convert_all_kernels_in_model(model1)

layer_utils_test.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

model = <keras.engine.sequential.Sequential object at 0x000001DB71977198>

    def convert_all_kernels_in_model(model):
        """Converts all convolution kernels in a model from Theano to TensorFlow.
    
        Also works from TensorFlow to Theano.
    
        # Arguments
            model: target model for the conversion.
        """
        # Note: SeparableConvolution not included
        # since only supported by TF.
        conv_classes = {
            'Conv1D',
            'Conv2D',
            'Conv3D',
            'Conv2DTranspose',
        }
        to_assign = None
        for layer in model.layers:
            if layer.__class__.__name__ in conv_classes:
                original_kernel = K.get_value(layer.kernel)
                converted_kernel = convert_kernel(original_kernel)
>               to_assign.append((layer.kernel, converted_kernel))
E               AttributeError: 'NoneType' object has no attribute 'append'

C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\keras\utils\layer_utils.py:215: AttributeError
---------------------------- Captured stderr call -----------------------------
Using TensorFlow backend.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-10-04 18:14:37.875456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-04 18:14:38.015946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-04 18:14:38.017183: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-04 18:14:38.022293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-04 18:14:38.027034: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-04 18:14:38.028885: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-04 18:14:38.035452: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-04 18:14:38.039909: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-04 18:14:38.052016: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-04 18:14:38.053161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-04 18:14:38.053985: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-04 18:14:38.068666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-04 18:14:38.069312: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-04 18:14:38.069752: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-04 18:14:38.070185: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-04 18:14:38.070618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-04 18:14:38.071008: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-04 18:14:38.071380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-04 18:14:38.071729: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-04 18:14:38.072687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-04 18:14:39.169836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-04 18:14:39.170315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-04 18:14:39.170599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-04 18:14:39.171442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

2020-10-04 18:14:39.770858: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-04 18:14:42.057272: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-10-04 18:14:42.082375: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
------------------------------ Captured log call ------------------------------
WARNING  tensorflow:deprecation.py:506 From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING  tensorflow:module_wrapper.py:139 From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.
=========================== short test summary info ===========================
FAILED layer_utils_test.py::test_convert_weights - AttributeError: 'NoneType'...
============================== 1 failed in 5.70s ==============================
