2020-10-06 16:35:42.673705: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Running tests under Python 3.6.12: C:\ProgramData\Anaconda3\envs\keras\python.exe
[ RUN      ] ControlFlowTest.test_for_composite_state_initialized_in_loop
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W1006 16:35:46.163026 20900 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2020-10-06 16:35:46.175406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-06 16:35:46.300645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:46.301173: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:46.304614: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:46.308077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:46.309692: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:46.314681: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:46.317893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:46.327261: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:46.328234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:46.328943: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-06 16:35:46.344507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:46.345077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:46.345463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:46.345804: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:46.346141: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:46.346478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:46.346820: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:46.347162: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:46.348009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:47.285400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:47.285810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:47.286101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:47.286895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x000001AD22E13B00>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "control_flow_test.py", line 874, in test_for_composite_state_initialized_in_loop
    constant_op.constant(list(range(5))), constant_op.constant(5))  File "C:\Users\mutation\AppData\Local\Temp\tmpin1jokhb.py", line 30, in test_fn
    ag__.for_stmt(n, None, loop_body, get_state_1, set_state_1, (), (), ('tc.x',))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 319, in for_stmt
    composite_symbol_names)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 400, in _known_len_tf_for_stmt
    opts=opts,  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
E1006 16:35:47.818949 20900 tf_should_use.py:76] ==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x000001AD22E13B00>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "control_flow_test.py", line 874, in test_for_composite_state_initialized_in_loop
    constant_op.constant(list(range(5))), constant_op.constant(5))  File "C:\Users\mutation\AppData\Local\Temp\tmpin1jokhb.py", line 30, in test_fn
    ag__.for_stmt(n, None, loop_body, get_state_1, set_state_1, (), (), ('tc.x',))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 319, in for_stmt
    composite_symbol_names)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 400, in _known_len_tf_for_stmt
    opts=opts,  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x000001AD22E13C50>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 319, in for_stmt
    composite_symbol_names)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 400, in _known_len_tf_for_stmt
    opts=opts,  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 1149, in unstack
    return self._implementation.unstack(value, name=name)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
E1006 16:35:47.818949 20900 tf_should_use.py:76] ==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x000001AD22E13C50>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 319, in for_stmt
    composite_symbol_names)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 400, in _known_len_tf_for_stmt
    opts=opts,  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 1149, in unstack
    return self._implementation.unstack(value, name=name)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x000001AD22E13BE0>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 1149, in unstack
    return self._implementation.unstack(value, name=name)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 320, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
E1006 16:35:47.818949 20900 tf_should_use.py:76] ==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x000001AD22E13BE0>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 1149, in unstack
    return self._implementation.unstack(value, name=name)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 320, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
[       OK ] ControlFlowTest.test_for_composite_state_initialized_in_loop
[ RUN      ] ControlFlowTest.test_for_iterated_expression
[       OK ] ControlFlowTest.test_for_iterated_expression
[ RUN      ] ControlFlowTest.test_for_single_output
2020-10-06 16:35:47.925393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:47.925928: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:47.926274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:47.926641: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:47.926981: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:47.927329: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:47.927679: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:47.928024: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:47.929066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:47.929707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:47.930412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:47.930861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:47.931802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_for_single_output
[ RUN      ] ControlFlowTest.test_for_tuple_unpacking
2020-10-06 16:35:48.041748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.043461: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.044598: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.045543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.046266: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.046991: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.047730: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.048480: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.049631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.050278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.051027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.051498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.052478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_for_tuple_unpacking
[ RUN      ] ControlFlowTest.test_for_with_comprehension_in_body
2020-10-06 16:35:48.105013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.105553: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.105916: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.106294: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.106658: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.107028: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.107396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.107765: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.108381: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.108713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.109089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.109342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.109882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_for_with_comprehension_in_body
[ RUN      ] ControlFlowTest.test_if_basic
[  FAILED  ] ControlFlowTest.test_if_basic
[ RUN      ] ControlFlowTest.test_if_complex_outputs
2020-10-06 16:35:48.254574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.255111: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.255460: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.255805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.256153: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.256521: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.256893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.257241: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.257824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.258138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.258490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.258710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.259222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_if_complex_outputs
[ RUN      ] ControlFlowTest.test_if_local_var
2020-10-06 16:35:48.318758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.319381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.319755: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.320124: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.320492: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.320834: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.321189: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.321542: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.322127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.322448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.322805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.323027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.323534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] ControlFlowTest.test_if_local_var
[ RUN      ] ControlFlowTest.test_if_no_outputs
2020-10-06 16:35:48.367240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.367787: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.368137: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.368486: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.368823: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.369167: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.369509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.369852: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.370427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.370739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.371108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.371329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.371845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_if_no_outputs
[ RUN      ] ControlFlowTest.test_if_semi
2020-10-06 16:35:48.432969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.433500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.433841: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.434197: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.434544: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.434891: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.435239: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.435581: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.436148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.436461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.436816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.437037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.437554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] ControlFlowTest.test_if_semi
[ RUN      ] ControlFlowTest.test_if_single_output
2020-10-06 16:35:48.477730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.478265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.478611: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.478956: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.479292: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.479648: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.480002: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.480353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.480922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.481232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.481585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.481805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.482320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] ControlFlowTest.test_if_single_output
[ RUN      ] ControlFlowTest.test_if_sparse_tensor
2020-10-06 16:35:48.518932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.519464: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.519809: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.520158: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.520495: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.520839: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.521183: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.521534: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.522126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.522435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.522792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.523012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.523519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] ControlFlowTest.test_if_sparse_tensor
[ RUN      ] ControlFlowTest.test_if_unbalanced_composite
2020-10-06 16:35:48.566153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.566685: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.567051: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.567396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.567733: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.568073: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.568420: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.568762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.569464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.569857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.570274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.570498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.571066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] ControlFlowTest.test_if_unbalanced_composite
[ RUN      ] ControlFlowTest.test_if_unbalanced_multiple_composites
2020-10-06 16:35:48.621994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.622522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.622867: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.623231: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.623576: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.623918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.624261: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.624603: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.625176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.625491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.625848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.626072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.626597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] ControlFlowTest.test_if_unbalanced_multiple_composites
[ RUN      ] ControlFlowTest.test_session
[  SKIPPED ] ControlFlowTest.test_session
[ RUN      ] ControlFlowTest.test_simple_for
2020-10-06 16:35:48.689921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.690455: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.690804: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.691149: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.691485: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.691836: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.692199: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.692553: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.693121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.693431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.693792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.694015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.694523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_simple_for
[ RUN      ] ControlFlowTest.test_while_basic
2020-10-06 16:35:48.841786: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.842442: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.842851: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.843261: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.843663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.844073: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.844484: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.844906: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.845592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.845967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.846393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.846658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.847245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_basic
[ RUN      ] ControlFlowTest.test_while_composite_state
2020-10-06 16:35:48.899175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.899729: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.900108: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.900453: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.900794: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.901140: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.901483: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.901831: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.902402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.902718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.903077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.903303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.903822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_composite_state
[ RUN      ] ControlFlowTest.test_while_composite_state_initialized_in_loop
2020-10-06 16:35:48.974873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:48.975931: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:48.976612: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:48.977294: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:48.977965: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:48.978650: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:48.979339: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:48.980038: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:48.980845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:48.981217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:48.981644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:48.981906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:48.982493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_composite_state_initialized_in_loop
[ RUN      ] ControlFlowTest.test_while_dispatches_by_cond_only
2020-10-06 16:35:49.048702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:49.049235: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:49.049581: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:49.049922: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:49.050259: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:49.050602: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:49.050943: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:49.051302: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:49.051882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:49.052204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:49.052560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:49.052783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:49.053295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_dispatches_by_cond_only
[ RUN      ] ControlFlowTest.test_while_local_composite
2020-10-06 16:35:49.107941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:49.108477: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:49.108818: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:49.109165: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:49.109501: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:49.109848: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:49.110191: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:49.110539: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:49.111126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:49.111436: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:49.111787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:49.112010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:49.112512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_local_composite
[ RUN      ] ControlFlowTest.test_while_local_composite_complex_illegal
[       OK ] ControlFlowTest.test_while_local_composite_complex_illegal
[ RUN      ] ControlFlowTest.test_while_local_composite_complex_nestable
2020-10-06 16:35:49.198518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:49.199059: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:49.199419: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:49.199771: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:49.200107: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:49.200450: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:49.200793: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:49.201135: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:49.201717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:49.202028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:49.202381: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:49.202618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:49.203113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_local_composite_complex_nestable
[ RUN      ] ControlFlowTest.test_while_nested
2020-10-06 16:35:49.264189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:49.264720: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:49.265068: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:49.265411: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:49.265755: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:49.266118: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:49.266470: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:49.266818: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:49.267383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:49.267693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:49.268047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:49.268267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:49.268764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_nested
[ RUN      ] ControlFlowTest.test_while_nested_composite_state
2020-10-06 16:35:49.338913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:49.339450: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:49.339797: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:49.340140: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:49.340482: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:49.340819: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:49.341164: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:49.341536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:49.342109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:49.342419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:49.342772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:49.342993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:49.343491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_nested_composite_state
[ RUN      ] ControlFlowTest.test_while_single_output
2020-10-06 16:35:49.373710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:35:49.374255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:35:49.374599: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:35:49.374948: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:35:49.375286: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:35:49.375631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:35:49.375974: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:35:49.376316: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:35:49.376881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:35:49.377193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:35:49.377546: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:35:49.377783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:35:49.378285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_single_output
======================================================================
ERROR: test_if_basic (__main__.ControlFlowTest)
ControlFlowTest.test_if_basic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 464, in test_if_basic
    self.assertTransformedResult(test_fn, constant_op.constant(1), (-1, 0))
  File "control_flow_test.py", line 60, in assertTransformedResult
    self.assertAllEqual(self.evaluate(result.test_fn(*inputs)), expected)
  File "C:\Users\mutation\AppData\Local\Temp\tmpvgrtckyv.py", line 20, in test_fn
    a, b = ag__.if_stmt(cond, if_true, if_false, get_state, set_state, ('a', 'b'), ())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 547, in __iter__
    self._disallow_iteration()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 543, in _disallow_iteration
    self._disallow_in_graph_mode("iterating over `tf.Tensor`")
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 523, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

======================================================================
FAIL: test_if_local_var (__main__.ControlFlowTest)
ControlFlowTest.test_if_local_var
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 602, in test_if_local_var
    self.assertTransformedResult(test_fn, constant_op.constant(1), 5)
  File "control_flow_test.py", line 60, in assertTransformedResult
    self.assertAllEqual(self.evaluate(result.test_fn(*inputs)), expected)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1122, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 2498, in assertAllEqual
    " Contents: %s. \n%s." % (a.shape, b.shape, b, msg))
AssertionError: Tuples differ: (1,) != ()

First tuple contains 1 additional elements.
First extra element 0:
1

- (1,)
+ () : Shape mismatch: expected (1,), got (). Contents: 5. 
.

======================================================================
FAIL: test_if_semi (__main__.ControlFlowTest)
ControlFlowTest.test_if_semi
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 578, in test_if_semi
    self.assertTransformedResult(test_fn, constant_op.constant(2), 3)
  File "control_flow_test.py", line 60, in assertTransformedResult
    self.assertAllEqual(self.evaluate(result.test_fn(*inputs)), expected)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1122, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 2498, in assertAllEqual
    " Contents: %s. \n%s." % (a.shape, b.shape, b, msg))
AssertionError: Tuples differ: (1,) != ()

First tuple contains 1 additional elements.
First extra element 0:
1

- (1,)
+ () : Shape mismatch: expected (1,), got (). Contents: 3. 
.

======================================================================
FAIL: test_if_single_output (__main__.ControlFlowTest)
ControlFlowTest.test_if_single_output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 558, in test_if_single_output
    self.assertTransformedResult(test_fn, constant_op.constant(1), -1)
  File "control_flow_test.py", line 60, in assertTransformedResult
    self.assertAllEqual(self.evaluate(result.test_fn(*inputs)), expected)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1122, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 2498, in assertAllEqual
    " Contents: %s. \n%s." % (a.shape, b.shape, b, msg))
AssertionError: Tuples differ: (1,) != ()

First tuple contains 1 additional elements.
First extra element 0:
1

- (1,)
+ () : Shape mismatch: expected (1,), got (). Contents: -1. 
.

======================================================================
FAIL: test_if_sparse_tensor (__main__.ControlFlowTest)
ControlFlowTest.test_if_sparse_tensor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "control_flow_test.py", line 488, in test_if_sparse_tensor
    self.assertTransformedResult(test_fn, (st, constant_op.constant(1)), -1)
  File "control_flow_test.py", line 60, in assertTransformedResult
    self.assertAllEqual(self.evaluate(result.test_fn(*inputs)), expected)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1122, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 2498, in assertAllEqual
    " Contents: %s. \n%s." % (a.shape, b.shape, b, msg))
AssertionError: Tuples differ: (1,) != ()

First tuple contains 1 additional elements.
First extra element 0:
1

- (1,)
+ () : Shape mismatch: expected (1,), got (). Contents: -1. 
.

======================================================================
FAIL: test_if_unbalanced_composite (__main__.ControlFlowTest)
ControlFlowTest.test_if_unbalanced_composite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 718, in test_if_unbalanced_composite
    (7, 13))
  File "control_flow_test.py", line 60, in assertTransformedResult
    self.assertAllEqual(self.evaluate(result.test_fn(*inputs)), expected)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1122, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 2523, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\numpy\testing\_private\utils.py", line 936, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\numpy\testing\_private\utils.py", line 846, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

not equal where = (array([1], dtype=int64),)
not equal lhs = [(13,)]
not equal rhs = [13]
Mismatched elements: 1 / 2 (50%)
 x: array([7, (13,)], dtype=object)
 y: array([ 7, 13])

======================================================================
FAIL: test_if_unbalanced_multiple_composites (__main__.ControlFlowTest)
ControlFlowTest.test_if_unbalanced_multiple_composites
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 674, in test_if_unbalanced_multiple_composites
    (7, 11, 13))
  File "control_flow_test.py", line 60, in assertTransformedResult
    self.assertAllEqual(self.evaluate(result.test_fn(*inputs)), expected)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1122, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 2523, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\numpy\testing\_private\utils.py", line 936, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\numpy\testing\_private\utils.py", line 846, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

not equal where = (array([2], dtype=int64),)
not equal lhs = [(13,)]
not equal rhs = [13]
Mismatched elements: 1 / 3 (33.3%)
 x: array([7, 11, (13,)], dtype=object)
 y: array([ 7, 11, 13])

----------------------------------------------------------------------
Ran 26 tests in 3.968s

FAILED (failures=6, errors=1, skipped=1)